server:
  port: 8081
  servlet:
    context-path: /api/community

spring:
  application:
    name: ms-communities
  jpa:
    show-sql: false

kafka:
  topic:
    listener_user: bleiny_community_topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka