server:
  port: 8080
  servlet:
    context-path: /bleiny-core
spring:
  jpa:
    database: MYSQL

  datasource:
    url: jdbc:mysql://localhost:3306/bleiny?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: docker

  application:
    name: bleiny-core

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka

kafka:
  topics:
    community_topic: bleiny_community_topic

log:
  retention:
    hours: 5
